### PR TITLE
Change to GoQuery

### LINKED ISSUE #21: Scrape company information
Currently only the company name is saved.

Change it so that the following information are also scraped and saved.

- Logo
- General information
- Contact
- etc

### LINKED ISSUE #31: Changing scraper logic to be more resilient
Currently with go-colly, there is a potential issue where if 1 page fails to load then the data is considered corrupted because we need the whole set of data in order to determine which job listings are active or inactive.

There is no retry functionality in go-colly and error handling is not very useful.

I think it might be better for us to fetch the html as string (where we can have our own retry logic) then use an HTML parser to process the data instead.

This will be more similar to the logic of the scraper in the .NET version.

Get html node in go with css selector: https://github.com/PuerkitoBio/goquery

Retry: https://github.com/avast/retry-go

### LINKED ISSUE #32: Minify scraped html before storing it
https://github.com/tdewolff/minify

### PR DESCRIPTION
**Pull request by syahnur197**
Changed scraper and added retry: Closes #31

Add minifier: Closes #32 

Add more job information: Closes #21

### CODE REVIEW

File: pkg/scraper/bruneida_scraper.go [hunk 1]
```diff
@@ -1,73 +1,127 @@
...
 
-			if strings.Contains(title, "City") || strings.Contains(title, "Local") {
-				locations = append(locations, child.ChildText(".dd"))
+			if err != nil {
+				continue
 			}
-		})
 
-		location := strings.Join(locations, " ")
+			jobs = append(jobs, *job)
```
Comment (dsychin) [inline pkg/scraper/bruneida_scraper.go:32]: You can change `jobs` to be a `[]*model.Job` if you don't want to have to convert job to value just to append it.

File: pkg/scraper/bruneida_scraper.go [hunk 2]
```diff
@@ -1,73 +1,127 @@
...
-		locations := []string{}
-		h.ForEach("#ad-body-inner .opt .opt-dl", func(i int, child *colly.HTMLElement) {
-			title := child.ChildText(".dt")
+		for _, link := range links {
+			job, err := scrapeBruneidaJob(link)
 
-			if strings.Contains(title, "City") || strings.Contains(title, "Local") {
-				locations = append(locations, child.ChildText(".dd"))
+			if err != nil {
+				continue
```
Comment (dsychin) [inline pkg/scraper/bruneida_scraper.go:29]: Should log this so that we know an error has happened

File: pkg/scraper/jobcenter_scraper.go [hunk 3]
```diff
@@ -1,53 +1,107 @@
...
+
+	doc.Find("li.list-group-item.list-group-item-flex").EachWithBreak(func(i int, s *goquery.Selection) bool {
+		jobTitle := s.Find(".jp_job_post_right_cont h4 a").Text()
+		company := s.Find(".jp_job_post_right_cont p a").Text()
+		salary := s.Find(".jp_job_post_right_cont>ul li:first-child").Text()
+		location := s.Find(".jp_job_post_right_cont>ul li:nth-child(2)").Text()
+		link, exist := s.Find(".jp_job_post_right_cont h4 a").Attr("href")
+
+		if !exist {
+			return true
```
[the remark this answers is not in the document]
Comment (syahnur197) [reply pkg/scraper/jobcenter_scraper.go:38]: return false will terminate the whole loop, I want it to continue looping

File: pkg/scraper/bruneida_scraper.go [hunk 4]
```diff
@@ -1,73 +1,127 @@
...
-		})
-	})
+		links, err := getJobLinks(url)
 
-	// Scraping the jobs
-	jobCollector.OnHTML("body", func(h *colly.HTMLElement) {
-		job_title := h.ChildText("#title-box-inner div.inline-block.pull-left h1")
-		company := h.ChildText("#ad-contact ul li:first-child span.bb b.small")
-		salary := h.ChildText("#ad-body-inner .opt .opt-dl:nth-child(3) .dd")
+		if err != nil {
```
[the remark this answers is not in the document]
Comment (syahnur197) [reply pkg/scraper/bruneida_scraper.go:21]: I don't get it

[the remark this answers is not in the document]
Comment (dsychin) [reply pkg/scraper/bruneida_scraper.go:21]: basically just do
```go
err = myfunc()
if err != nil {
```

instead of 
```go
err = myfunc()

if err != nil {
```

File: pkg/scraper/jobcenter_scraper.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (dsychin) [reply pkg/scraper/jobcenter_scraper.go:38]: Oh ok, it is specific to doc.Find.EachWithBreak

File: pkg/scraper/scraper.go [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+		if err != nil {
+			return err
+		}
+
+		defer res.Body.Close()
+
+		if res.StatusCode != 200 {
+			errorMessage := fmt.Sprintf("status code error: %d %s", res.StatusCode, res.Status)
+
+			log.Fatal(errorMessage)
```
Comment (dsychin) [inline pkg/scraper/scraper.go:35]: I think you're looking for `log.Error`? `log.Fatal` will kill the program.

File: pkg/scraper/scraper.go [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+	err := retry.Do(func() error {
+
+		res, err := http.Get(url)
+		if err != nil {
+			return err
+		}
+
+		defer res.Body.Close()
+
+		if res.StatusCode != 200 {
```
Comment (dsychin) [inline pkg/scraper/scraper.go:32]: You can make this more readable using the http Status const.

```
res.StatusCode != http.StatusOK
```

**Review by dsychin — CHANGES_REQUESTED** [review]

File: pkg/scraper/scraper.go (hunk 5 above)
Comment (syahnur197) [reply pkg/scraper/scraper.go]: log.Error is not in the standard log package

File: pkg/controller/controller.go [hunk 7]
```diff
@@ -10,7 +12,7 @@ type Controller struct {
 }
 
 func Ping(c *gin.Context) {
```
Comment (dsychin) [inline pkg/controller/controller.go:14]: I deleted this func in main, so I think you will need to merge main and resolve the conflict

File: pkg/scraper/scraper.go [hunk 8]
```diff
@@ -29,10 +28,10 @@ func getDocument(url string) (*goquery.Document, error) {
 
 		defer res.Body.Close()
 
-		if res.StatusCode != 200 {
+		if res.StatusCode != http.StatusOK {
 			errorMessage := fmt.Sprintf("status code error: %d %s", res.StatusCode, res.Status)
 
-			log.Fatal(errorMessage)
+			fmt.Println(errorMessage)
```
Comment (dsychin) [inline pkg/scraper/scraper.go:34]: print error for line 41 and 48 as well

**Review by dsychin — APPROVED** [review]

File: pkg/scraper/scraper.go (hunk 8 above)
Comment (dsychin) [reply pkg/scraper/scraper.go:34]: Just for your info, you can use `log.Print` alternatively, the difference is that it includes a timestamp. Which is useful for tracking an issue in production.

We will probably change to use zerolog's `log.Error().Msg("some error")` as that will include log level, timestamp and optionally objects, data, etc.
